### ISSUE TITLE
Server Crashes When i restart server after putting phar in plugin folder

### ISSUE THREAD

**Issue by Vodkafroggie101** [Heisenburger69/BurgerCustomArmor#11]
5.05 09:34:15 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected ')'" (EXCEPTION) in "plugins/BurgerCustomArmor_dev-21.phar/src/Heisenburger69/BurgerCustomArmor/Main" at line 140
05.05 09:34:15 [Server] Server thread/DEBUG #0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[37] Heisenburger69\BurgerCustomArmor\Main)
05.05 09:34:15 [Server] Server thread/DEBUG #1 (): BaseClassLoader->{closure}(string[37] Heisenburger69\BurgerCustomArmor\Main)
05.05 09:34:15 [Server] Server thread/DEBUG #2 (): spl_autoload_call(string[37] Heisenburger69\BurgerCustomArmor\Main)
05.05 09:34:15 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(165): class_exists(string[37] Heisenburger69\BurgerCustomArmor\Main, boolean 1)
05.05 09:34:15 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(335): pocketmine\plugin\PluginManager->loadPlugin(string[84] /plugins/BurgerCustomArmor_dev-21., array[2])
05.05 09:34:15 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1527): pocketmine\plugin\PluginManager->loadPlugins(string[55] /plugins/)
05.05 09:34:15 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
05.05 09:34:15 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(296): pocketmine\server()
05.05 09:34:15 [Server] Server thread/DEBUG #8 (11): require(string[103] phar:///jar/pocketmine.phar/src/po)

**Comment by Heisenburger69** [comment]
Please update your PHP version to PHP 7.3
