### ISSUE TITLE
Items returning to inventory after a armor piece is made

### ISSUE THREAD

**Issue by CrafterLTU** [Heisenburger69/BurgerCustomArmor#12]
![Armor](https://user-images.githubusercontent.com/50147743/83743522-80236d80-a663-11ea-9c61-4a86f18282d7.gif)

I use server.pro to host my server, if you need further info i can try and provide you with as much as i can on my discord SportyBadge#3700

**Comment by Heisenburger69** [comment]
Was fixed in https://github.com/Heisenburger69/BurgerCustomArmor/commit/31347dca319b0451c71269f1e7d15828f547c90f but issue still occurs on high latencies
