### ISSUE TITLE
Not really an issue, but a suggestion

### ISSUE THREAD

**Issue by CrafterLTU** [Heisenburger69/BurgerCustomArmor#14]
I'd love it if the set bonuses affected mobs, it would really open up a lot of ideas, unless you don't think its needed, i don't know, just a suggestion, i don't know about others but i'd love to see that maybe in the future.

**Comment by Heisenburger69** [comment]
Most of the abilities, both defensive and offensive work on the principle of checking whether the opponent/player you're attacking is holding a specific item, f.e: SwordAmplificationAbility does extra damage if the opponent is holding a sword. There's no reliable way to check what an entity is holding, so I won't be implementing this.
