### ISSUE TITLE
Request an update.

### ISSUE THREAD

**Issue by Arata-Tempest** [Heisenburger69/BurgerCustomArmor#26]
.Please create a plugin like this but for other items like Sword and Bow
Make it customizable from within the game and build a custom Armor game from within

And also in the recipes section, please do something so that the item needed to make it is set, 
for example [[[264:0:10:Enchanted Diamond:perotaction:1]]] I mean add a custom name and enchant to it

**Comment by Heisenburger69** [comment]
Weapons have already been suggested. The second is not possible at this moment in PM
