### ISSUE TITLE
Strenght doesn't work

### ISSUE THREAD

**Issue by MpLLLL71** [Heisenburger69/BurgerCustomArmor#3]
I have set strenght like diamond on chainmail tier:

strength:
    helmet: 3
    chestplate: 8
    leggings: 6
    boots: 3

But it doesn't work :/

**Comment by Heisenburger69** [comment]
This plugin doesn't cause all chainmail tier armor to be that strong. Only the specific armor set becomes that strong

**Comment by Heisenburger69** [comment]
oops, the method was implemented but never called

**Comment by Heisenburger69** [comment]
Fixed in https://github.com/Heisenburger69/BurgerCustomArmor/commit/d1cec0e41b396e87c26cfd4047596d61310dd152
