### ISSUE TITLE
More Armor Abilites

### ISSUE THREAD

**Issue by reactwindd** [Heisenburger69/BurgerCustomArmor#31]
Undead Amplification ( Smite lol )
Unused Amplification 
Fish Amplification ( Impaling lol )
Slime-Type Amplification ( Cubism lol )
Arthropods Amplification ( bane of arthropods lol )

**Comment by reactwindd** [comment]
https://minecraftfanon.fandom.com/wiki/Category:Mobs more info

**Comment by varunbln** [comment]
Those are very specific and will not be added to this plugin
