### ISSUE TITLE
API For Defense Point

### ISSUE THREAD

**Issue by reactwindd** [Heisenburger69/BurgerCustomArmor#34]
How can I a API for the Armor Strength?
![image](https://user-images.githubusercontent.com/71582030/126040270-e5c8bb31-cb81-4983-a012-e35bd17cd455.png)

I am editing a plugin, so that its compatible with BCA ( Burger Custom Armor )
![image](https://user-images.githubusercontent.com/71582030/126040402-5e0de169-ebae-4a2c-b76e-6c90d96fe1f9.png)

**Comment by reactwindd** [comment]
uh @Heisenburger69, can I hve the API of it?

**Comment by varunbln** [comment]
Unfortunately this does not exist at the moment, the plugin is not being worked on anymore
