### ISSUE TITLE
Idea: Set Durability of each pièce of armor

### ISSUE THREAD

**Issue by MpLLLL71** [Heisenburger69/BurgerCustomArmor#4]
Hi. This is a suggestion.

Set durability of each piece of armor like armorpoint with:

public function getMaxDurability() : int{

  durability:
    helmet: 196
    chestplate: 241
    leggings: 166
    boots: 226

**Comment by Heisenburger69** [comment]
Already on the Todo

**Comment by Heisenburger69** [comment]
Implemented in latest build
